// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACXBIRO_B2_kNLf5_KpJjmBF2mYoi6mHo',
    appId: '1:748582012794:web:f2eb573ddb475bafe9b8c3',
    messagingSenderId: '748582012794',
    projectId: 'flutteriti-f73e7',
    authDomain: 'flutteriti-f73e7.firebaseapp.com',
    storageBucket: 'flutteriti-f73e7.firebasestorage.app',
    measurementId: 'G-GYDRKK5LS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1XOKBsCQGkDwmkllh23INIAJ19JwfwtU',
    appId: '1:748582012794:android:9ae19b33fc04d261e9b8c3',
    messagingSenderId: '748582012794',
    projectId: 'flutteriti-f73e7',
    storageBucket: 'flutteriti-f73e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcYTkTyrCaAwQNEw9FaQFmY06smou_aKQ',
    appId: '1:748582012794:ios:92f6c47a5b011df8e9b8c3',
    messagingSenderId: '748582012794',
    projectId: 'flutteriti-f73e7',
    storageBucket: 'flutteriti-f73e7.firebasestorage.app',
    iosBundleId: 'com.example.firebaseiti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcYTkTyrCaAwQNEw9FaQFmY06smou_aKQ',
    appId: '1:748582012794:ios:92f6c47a5b011df8e9b8c3',
    messagingSenderId: '748582012794',
    projectId: 'flutteriti-f73e7',
    storageBucket: 'flutteriti-f73e7.firebasestorage.app',
    iosBundleId: 'com.example.firebaseiti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACXBIRO_B2_kNLf5_KpJjmBF2mYoi6mHo',
    appId: '1:748582012794:web:6cd77ac1dc72aae9e9b8c3',
    messagingSenderId: '748582012794',
    projectId: 'flutteriti-f73e7',
    authDomain: 'flutteriti-f73e7.firebaseapp.com',
    storageBucket: 'flutteriti-f73e7.firebasestorage.app',
    measurementId: 'G-6X49B4EW1L',
  );
}
